name: dart_console
version: 1.1.2
homepage: https://github.com/timsneath/dart_console
description: 
  A helper library for command-line applications that need more control over input/output than the standard library provides.

environment:
  sdk: '>=2.17.0 <3.0.0'

# Explicitly declare that this package works on all desktop platforms.
platforms:
  linux:
  macos:
  windows:

dependencies:
  ffi: '>=1.0.0 <3.0.0'
  win32: ^3.0.0
  intl: ^0.17.0
  characters: ^1.2.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
